import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import MaterialUiProvider from "@/providers/MaterialUiProvider";
import TanStackQueryProvider from "@/providers/TanStackQueryProvider";

export type RootLayoutProps = Readonly<{
  children: React.ReactNode;
}>;

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TanStackQueryProvider>
          <MaterialUiProvider>{children}</MaterialUiProvider>
        </TanStackQueryProvider>
      </body>
    </html>
  );
}
